### ISSUE TITLE
tsung multipart/form-data

### ISSUE THREAD

**Issue by Qdo45** [processone/tsung#285]
Hi. i cant use this metod...

config:

<?xml version="1.0"?>
<!DOCTYPE tsung SYSTEM "/usr/share/tsung/tsung-1.0.dtd">
<tsung loglevel="debug" version="1.0">
  <clients>
    <client host="localhost" use_controller_vm="true" maxusers="10" />
  </clients>
 
  <servers>
    <server host="test" port="8000" type="tcp" /> 
  </servers>
 
  <load>
    <arrivalphase phase="1" duration="1" unit="second">
        <users maxnumber="10" arrivalrate="1" unit="second" />
    </arrivalphase>
  </load>
 
 
  <sessions>
    <session name='rec20140402-1908' probability='100'  type='ts_http'>
<request>
<http url='/api/regis' 
version='1.1' 
content_type='multipart/form-data; 
boundary=------WebKitFormBoundary7MA4YWxkTrZu0gW'
contents_from_file='/home/qdos/22.bin'
method='POST'>
</http>
</request>  
    </session>
  </sessions>
</tsung>

File:
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="token"
c7be5a2438f243f6b369fcaa6f266e38
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="lang"
rus
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="name"
2222
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="/home/qdos/ba59ab04-a88c-41ba-aae6-79392ce7b2f8_15168691868394264765827460068741.xls"
Content-Type: application/vnd.ms-excel
------WebKitFormBoundary7MA4YWxkTrZu0gW--

What's wrong with what I'm doing? dont work...

**Comment by Bryinn** [comment]
Hello, I seem to be having the same problem with this. 
In my case, I am running a NextJS application, and it seems like it is not getting accepted by the TS type checker:

>  ⨯ TypeError: Failed to parse body as FormData.
>     at node:internal/deps/undici/undici:4235:27
>     at successSteps (node:internal/deps/undici/undici:4274:27)
>     at fullyReadBody (node:internal/deps/undici/undici:2695:9)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at async consumeBody (node:internal/deps/undici/undici:4283:7)
>     at async /app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:15:6917
>     at async rm (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:15:6342)
>     at async rq (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:18:1249)
>     at async doRender (/app/node_modules/next/dist/server/base-server.js:1378:30)
>     at async cacheEntry.responseCache.get.routeKind (/app/node_modules/next/dist/server/base-server.js:1539:28)

I am running the traffic generated by the tsung recorder, to make sure everything is correct. The server itself simply do not accept the imput it seems.
